question_data = [
        {"category": "Animals", "type": "boolean", "difficulty": "easy", "question": "A slug&rsquo;s blood is green.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Geography", "type": "boolean", "difficulty": "easy",
         "question": "The Republic of Malta is the smallest microstate worldwide.", "correct_answer": "False",
         "incorrect_answers": ["True"]}, {"category": "Art", "type": "boolean", "difficulty": "easy",
                                          "question": "Leonardo da Vinci&#039;s Mona Lisa does not have eyebrows.",
                                          "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The vapor produced by e-cigarettes is actually water.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "Shaquille O&#039;Neal appeared in the 1997 film &quot;Space Jam&quot;.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
         "question": "You can legally drink alcohol while driving in Mississippi.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science: Gadgets", "type": "boolean", "difficulty": "medium",
                                           "question": "The Western Electric Model 500 telephone uses tone dialing to dial phone numbers.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Animals", "type": "boolean", "difficulty": "easy",
         "question": "A flock of crows is known as a homicide.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In the game &quot;Subnautica&quot;, a &quot;Spadefish&quot; will attack you.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
                                           "question": "In the original Star Wars trilogy, Alec Guinness provided the voice for Darth Vader.",
                                           "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Sports", "type": "boolean", "difficulty": "medium",
         "question": "Formula E is an auto racing series that uses hybrid electric race cars.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In Portal, the Companion Cube&#039;s ARE sentient.", "correct_answer": "True",
         "incorrect_answers": ["False"]}, {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
                                           "question": "Psychology is the science of behavior and mind.",
                                           "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "In the &quot;Kagerou Daze&quot; series, Shintaro Kisaragi is prominently shown with the color red.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "The most frequent subconscious activity repeated by the human body is blinking.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Vehicles", "type": "boolean", "difficulty": "hard",
         "question": "The term &quot;GTO&quot; was originated by Ferrari?", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
         "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the final chapter of the game.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "hard",
         "question": "The protagonist in &quot;Humanity Has Declined&quot; has no discernable name and is simply referred to as &#039;I&#039; for most of the series.",
         "correct_answer": "True", "incorrect_answers": ["False"]}
]
